### ISSUE TITLE
ErrorOn Running

### ISSUE THREAD

**Issue by Ridham32** [Ridham32/ToDoApp#1]
Not able to run the app as it shows the error related to roomdatabase entity and dao annotations.

**Comment by fergaschas** [comment]
Update Room database dependencies to version 2.6.1:
`    //room database dependencies
    implementation("androidx.room:room-runtime:2.6.1")
    annotationProcessor("androidx.room:room-compiler:2.6.1" )
    kapt("androidx.room:room-compiler:2.6.1")
    //new dependencies for live data
    implementation("androidx.room:room-ktx:2.6.1")`

**Comment by Ridham32** [comment]
thanku, it works
